name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")
city = input("Which city are you from? ")

print("\nWelcome", name)
print("You are", age, "years old.")
print("Your favorite hobby is", hobby + ".")
print("You are from", city + ".")
print("Nice to meet you.")
